'use client';
import { useState } from 'react';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
export default function NewAgentPage(){
  const [step,setStep]=useState(1);
  const [name,setName]=useState('');
  const [desc,setDesc]=useState('');
  const [cat,setCat]=useState('trading');
  const [wallet,setWallet]=useState<{address:string;privateKey:string}|null>(null);
  const [loading,setLoading]=useState(false);
  const launch=async()=>{setLoading(true);const wr=await fetch('/api/wallet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'generate'})});const wd=await wr.json();setWallet(wd);await fetch('/api/agents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,description:desc,category:cat,walletAddress:wd.address})});setLoading(false);setStep(3);};
  return(<><Navbar /><main className="mx-auto max-w-2xl px-6 py-16"><h1 className="mb-8 text-3xl font-black">Launch Your Agent</h1><div className="mb-12 flex items-center gap-4">{[1,2,3].map(s=><div key={s} className="flex items-center gap-2"><div className={"flex h-8 w-8 items-center justify-center rounded-full text-sm font-bold "+(step>=s?"bg-[#a855f7] text-white":"bg-[#1a1a28] text-[#8888a0]")}>{s}</div><span className={step>=s?"text-white":"text-[#8888a0]"}>{s===1?"Basics":s===2?"Skills":"Launch"}</span></div>)}</div>
  {step===1&&<div className="space-y-6"><div><label className="mb-2 block text-sm text-[#8888a0]">Agent Name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. SolSniper..." className="w-full rounded-xl border border-[#2a2a3a] bg-[#12121a] px-4 py-3 text-white outline-none focus:border-[#a855f7]"/></div><div><label className="mb-2 block text-sm text-[#8888a0]">Description</label><textarea value={desc} onChange={e=>setDesc(e.target.value)} rows={3} placeholder="What does your agent do?" className="w-full rounded-xl border border-[#2a2a3a] bg-[#12121a] px-4 py-3 text-white outline-none focus:border-[#a855f7]"/></div><div><label className="mb-2 block text-sm text-[#8888a0]">Category</label><div className="flex flex-wrap gap-3">{['trading','defi','social','research','creative'].map(c=><button key={c} onClick={()=>setCat(c)} className={"rounded-full px-4 py-2 text-sm "+(cat===c?"bg-[#a855f7] text-white":"border border-[#2a2a3a] bg-[#12121a] text-[#8888a0]")}>{c}</button>)}</div></div><button onClick={()=>setStep(2)} disabled={!name} className="w-full rounded-xl bg-gradient-to-r from-[#6c5ce7] to-[#a855f7] py-3 font-bold text-white disabled:opacity-50">Continue</button></div>}
  {step===2&&<div className="space-y-6"><p className="text-[#8888a0]">Select skills:</p><div className="flex flex-wrap gap-3">{['Trading','DCA','Perps','Lending','Token Launch','Market Research'].map(s=><button key={s} className="rounded-full border border-[#2a2a3a] bg-[#12121a] px-4 py-2 text-sm text-[#8888a0]">{s}</button>)}</div><div className="flex gap-4"><button onClick={()=>setStep(1)} className="flex-1 rounded-xl border border-[#2a2a3a] bg-[#12121a] py-3 font-bold">Back</button><button onClick={()=>setStep(3)} className="flex-1 rounded-xl bg-gradient-to-r from-[#6c5ce7] to-[#a855f7] py-3 font-bold text-white">Continue</button></div></div>}
  {step===3&&!wallet&&<div className="space-y-6"><div className="rounded-2xl border border-[#2a2a3a] bg-[#12121a] p-6"><h3 className="mb-4 text-xl font-bold">Review</h3><div className="space-y-2 text-sm"><div className="flex justify-between"><span className="text-[#8888a0]">Name</span><span>{name}</span></div><div className="flex justify-between"><span className="text-[#8888a0]">Category</span><span>{cat}</span></div></div></div><div className="flex gap-4"><button onClick={()=>setStep(2)} className="flex-1 rounded-xl border border-[#2a2a3a] bg-[#12121a] py-3 font-bold">Back</button><button onClick={launch} disabled={loading} className="flex-1 rounded-xl bg-gradient-to-r from-[#00d68f] to-[#06b6d4] py-3 font-bold text-white disabled:opacity-50">{loading?'Launching...':'Launch Agent'}</button></div></div>}
  {step===3&&wallet&&<div className="rounded-2xl border-2 border-[#00d68f] bg-[#12121a] p-6 text-center"><div className="mb-4 text-5xl">🎉</div><h3 className="mb-2 text-xl font-bold text-[#00d68f]">Agent Launched!</h3><div className="mb-4 rounded-xl bg-[#0a0a0f] p-4"><div className="mb-1 text-xs text-[#8888a0]">Wallet Address</div><div className="font-mono text-sm break-all">{wallet.address}</div></div><div className="mb-6 rounded-xl border-2 border-[#ff4757] bg-[#0a0a0f] p-4"><div className="mb-1 text-xs font-bold text-[#ff4757]">SAVE THIS PRIVATE KEY — SHOWN ONCE</div><div className="font-mono text-xs break-all text-[#ffc048]">{wallet.privateKey}</div></div><a href="/dashboard" className="block w-full rounded-xl bg-gradient-to-r from-[#6c5ce7] to-[#a855f7] py-3 font-bold text-white">Go to Dashboard</a></div>}
  </main><Footer /></>);
}