'use client';
import { useState } from 'react';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
export default function RegisterPage(){
  const [email,setEmail]=useState('');
  const [username,setUsername]=useState('');
  const [wallet,setWallet]=useState<{address:string;privateKey:string}|null>(null);
  const [apiKey,setApiKey]=useState('');
  const [done,setDone]=useState(false);
  const [loading,setLoading]=useState(false);
  const register=async()=>{setLoading(true);const wr=await fetch('/api/wallet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'generate'})});const wd=await wr.json();setWallet(wd);const k='rdog_'+Array.from({length:48},()=>{const c='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';return c[Math.floor(Math.random()*c.length)]}).join('');setApiKey(k);setLoading(false);setDone(true);};
  return(<><Navbar /><main className="mx-auto max-w-lg px-6 py-16"><h1 className="mb-8 text-3xl font-black">Create Account</h1>{!done?(<div className="space-y-6"><div><label className="mb-2 block text-sm text-[#8888a0]">Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full rounded-xl border border-[#2a2a3a] bg-[#12121a] px-4 py-3 text-white outline-none focus:border-[#a855f7]" /></div><div><label className="mb-2 block text-sm text-[#8888a0]">Username</label><input value={username} onChange={e=>setUsername(e.target.value)} className="w-full rounded-xl border border-[#2a2a3a] bg-[#12121a] px-4 py-3 text-white outline-none focus:border-[#a855f7]" /></div><button onClick={register} disabled={!email||!username||loading} className="w-full rounded-xl bg-gradient-to-r from-[#6c5ce7] to-[#a855f7] py-3 font-bold text-white disabled:opacity-50">{loading?'Creating...':'Create Account & Wallet'}</button><p className="text-center text-sm text-[#8888a0]">Have account? <a href="/login" className="text-[#a855f7] hover:underline">Login</a></p></div>):wallet&&(<div className="rounded-2xl border-2 border-[#00d68f] bg-[#12121a] p-6 text-center"><div className="mb-4 text-5xl">🎉</div><h2 className="mb-2 text-xl font-bold text-[#00d68f]">Account Created!</h2><div className="mb-4 rounded-xl bg-[#0a0a0f] p-4 text-left"><div className="mb-1 text-xs text-[#8888a0]">Wallet</div><div className="font-mono text-sm break-all">{wallet.address}</div></div><div className="mb-4 rounded-xl bg-[#0a0a0f] p-4 text-left"><div className="mb-1 text-xs text-[#8888a0]">API Key</div><div className="font-mono text-sm break-all text-[#a855f7]">{apiKey}</div></div><div className="mb-6 rounded-xl border-2 border-[#ff4757] bg-[#0a0a0f] p-4 text-left"><div className="mb-1 text-xs font-bold text-[#ff4757]">SAVE PRIVATE KEY — SHOWN ONCE</div><div className="font-mono text-xs break-all text-[#ffc048]">{wallet.privateKey}</div></div><a href="/dashboard" className="block w-full rounded-xl bg-gradient-to-r from-[#6c5ce7] to-[#a855f7] py-3 font-bold text-white">Dashboard</a></div>)}</main><Footer /></>);
}
